#AndroidCS: enforce UTF-8 & locale for Gradle daemon
#Fri Oct 02 07:50:56 GMT 2026
org.gradle.caching=true
org.gradle.daemon.idletimeout=10800000
systemProp.user.language=en
systemProp.user.country=US
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding\=UTF-8
android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official
systemProp.sun.jnu.encoding=UTF-8
systemProp.file.encoding=UTF-8
